#!/bin/sh

# Application composition root for one-time server installation.

# shellcheck source=../helpers/common.sh
. "$EMAILWIZ_APP_DIR/helpers/common.sh"
# shellcheck source=options.sh
. "$EMAILWIZ_APP_DIR/installer/options.sh"
# shellcheck source=packages.sh
. "$EMAILWIZ_APP_DIR/installer/packages.sh"
# shellcheck source=postfix.sh
. "$EMAILWIZ_APP_DIR/installer/postfix.sh"
# shellcheck source=opendkim.sh
. "$EMAILWIZ_APP_DIR/installer/opendkim.sh"
# shellcheck source=security.sh
. "$EMAILWIZ_APP_DIR/installer/security.sh"
# shellcheck source=spamassassin.sh
. "$EMAILWIZ_APP_DIR/installer/spamassassin.sh"
# shellcheck source=services.sh
. "$EMAILWIZ_APP_DIR/installer/services.sh"
# shellcheck source=summary.sh
. "$EMAILWIZ_APP_DIR/installer/summary.sh"
# shellcheck source=../helpers/installer/certbot.sh
. "$EMAILWIZ_APP_DIR/helpers/installer/certbot.sh"

emailwiz_installer_validate_authenticator() {
	case "$certbot_authenticator" in
		dns-acme) emailwiz_certbot_validate_acme_dns_client "$acme_dns_client" ;;
		dns-cloudflare) emailwiz_certbot_validate_cloudflare_credentials "$cloudflare_credentials" ;;
	esac
}

emailwiz_installer_require_canonical_dns() {
	ipv4=$(host "$maildomain" 2>/dev/null | awk '/ has address / { print $NF; exit }')
	ipv6=$(host "$maildomain" 2>/dev/null | awk '/ has IPv6 address / { print $NF; exit }')
	[ -n "$ipv4$ipv6" ] || {
		printf '\033[0;31mPlease point %s to your server with an A and/or AAAA record.\033[0m\n' "$maildomain"
		exit 1
	}
}

emailwiz_installer_open_mail_ports() {
	# TCP/80 is deliberately left to the administrator. The HTTP-01 helper
	# prints the firewall prerequisite without modifying that rule.
	for port in 993 465 25 587 110 995; do
		ufw allow "$port" 2>/dev/null
	done
}

emailwiz_installer_main() {
	emailwiz_installer_parse_options "$@"
	emailwiz_installer_validate_authenticator
	emailwiz_installer_install_packages
	emailwiz_installer_install_application

	domain=$(cat /etc/mailname)
	subdom=mail
	maildomain="$subdom.$domain"
	allow_suboptimal_ciphers=yes

	# Fail early on unsupported Ubuntu/Dovecot versions and initialize the
	# virtual-domain database before changing service configuration.
	emailwiz_installer_run_management system init --spamassassin "$use_spamassassin"
	emailwiz_installer_require_canonical_dns
	emailwiz_installer_open_mail_ports

	certdir=$(emailwiz_certbot_run "$maildomain" "$certbot_authenticator" \
		"$acme_dns_client" "$cloudflare_credentials")

	[ -d "$certdir" ] || die "Error locating or installing SSL certificate directory: $certdir"
	[ -f "$certdir/fullchain.pem" ] || die 'Error locating or installing SSL certificate chain.'
	[ -f "$certdir/privkey.pem" ] || die 'Error locating or installing SSL certificate key.'
	[ -f "$certdir/cert.pem" ] || die 'Error locating or installing SSL leaf certificate.'

	# TLS identity belongs to the mail system, not to an individual hosted domain.
	emailwiz_installer_run_management system tls "$maildomain" --cert-dir "$certdir" \
		--authenticator "$certbot_authenticator" --no-reload
	emailwiz_installer_run_management domain add "$domain" --no-reload

	emailwiz_installer_configure_postfix
	echo "Dovecot $(dovecot --version) configuration was generated by emailwizctl."
	emailwiz_installer_configure_opendkim
	emailwiz_installer_configure_fail2ban
	emailwiz_installer_configure_spamassassin
	emailwiz_installer_finalize_services
	emailwiz_installer_print_summary
}
