#!/bin/sh

require_active_domains() {
	[ "$(active_domain_count)" -gt 0 ] || die "At least one active domain is required to render service configuration."
}

render_dovecot_tls_23() {
	load_canonical_tls
	printf 'ssl_cert = <%s/fullchain.pem\nssl_key = <%s/privkey.pem\n' \
		"$CANONICAL_CERT_DIR" "$CANONICAL_CERT_DIR"
}

render_dovecot_tls_24() {
	load_canonical_tls
	printf 'ssl_server_cert_file = %s/fullchain.pem\nssl_server_key_file = %s/privkey.pem\n' \
		"$CANONICAL_CERT_DIR" "$CANONICAL_CERT_DIR"
}

render_dovecot_23() {
	cat <<EOF
# Generated by emailwizctl for Dovecot $DOVECOT_VERSION. Do not edit manually.
ssl = required
ssl_min_protocol = TLSv1.2
ssl_prefer_server_ciphers = no
auth_mechanisms = plain login
auth_username_format = %Lu
protocols = imap pop3 lmtp

passdb {
    driver = sql
    args = $DOVECOT_SQL_CONF
}
userdb {
    driver = sql
    args = $DOVECOT_SQL_CONF
}

mail_location = maildir:~/Mail:INBOX=~/Mail/Inbox:LAYOUT=fs
namespace inbox {
    inbox = yes
    mailbox Drafts {
        special_use = \Drafts
        auto = subscribe
    }
    mailbox Junk {
        special_use = \Junk
        auto = subscribe
        autoexpunge = 30d
    }
    mailbox Sent {
        special_use = \Sent
        auto = subscribe
    }
    mailbox Trash {
        special_use = \Trash
    }
    mailbox Archive {
        special_use = \Archive
    }
}

service auth {
    unix_listener /var/spool/postfix/private/auth {
        mode = 0660
        user = postfix
        group = postfix
    }
}
service lmtp {
    unix_listener /var/spool/postfix/private/dovecot-lmtp {
        mode = 0600
        user = postfix
        group = postfix
    }
}

protocol lmtp {
    postmaster_address = postmaster@%d
    mail_plugins = \$mail_plugins sieve
}
protocol pop3 {
    pop3_no_flag_updates = yes
}

plugin {
    sieve = ~/.dovecot.sieve
    sieve_default = $SIEVE_DIR/default.sieve
    sieve_dir = ~/.sieve
    sieve_global_dir = $SIEVE_DIR
}
EOF
	render_dovecot_tls_23
}

render_dovecot_sql_23() {
	cat <<EOF
# Generated by emailwizctl for Dovecot 2.3.
driver = sqlite
connect = $DB_PATH
password_query = SELECT u.email AS user, u.password_hash AS password FROM mail_users u JOIN domains d ON d.id = u.domain_id WHERE u.email = lower('%u') AND u.enabled = 1 AND d.enabled = 1
user_query = SELECT u.home_path AS home, u.uid AS uid, u.gid AS gid FROM mail_users u JOIN domains d ON d.id = u.domain_id WHERE u.email = lower('%u') AND u.enabled = 1 AND d.enabled = 1
iterate_query = SELECT u.email AS user FROM mail_users u JOIN domains d ON d.id = u.domain_id WHERE u.enabled = 1 AND d.enabled = 1
EOF
}

render_dovecot_24() {
	cat <<EOF
dovecot_config_version = 2.4.0
dovecot_storage_version = 2.4.0
# Generated by emailwizctl for Dovecot $DOVECOT_VERSION. Do not edit manually.

ssl = required
ssl_min_protocol = TLSv1.2
ssl_server_prefer_ciphers = client
auth_mechanisms = plain login
auth_username_format = %{user | lower}
protocols {
    imap = yes
    pop3 = yes
    lmtp = yes
}

sql_driver = sqlite
sqlite_path = $DB_PATH
sqlite_readonly = yes
passdb sql {
    query = SELECT u.email AS user, u.password_hash AS password FROM mail_users u JOIN domains d ON d.id = u.domain_id WHERE u.email = lower('%{user}') AND u.enabled = 1 AND d.enabled = 1
}
userdb sql {
    query = SELECT u.home_path AS home, u.uid AS uid, u.gid AS gid FROM mail_users u JOIN domains d ON d.id = u.domain_id WHERE u.email = lower('%{user}') AND u.enabled = 1 AND d.enabled = 1
    iterate_query = SELECT u.email AS user FROM mail_users u JOIN domains d ON d.id = u.domain_id WHERE u.enabled = 1 AND d.enabled = 1
}

mail_driver = maildir
mail_path = ~/Mail
mail_inbox_path = ~/Mail/Inbox
mailbox_list_layout = fs
namespace inbox {
    inbox = yes
    mailbox Drafts {
        special_use = \Drafts
        auto = subscribe
    }
    mailbox Junk {
        special_use = \Junk
        auto = subscribe
        autoexpunge = 30d
    }
    mailbox Sent {
        special_use = \Sent
        auto = subscribe
    }
    mailbox Trash {
        special_use = \Trash
    }
    mailbox Archive {
        special_use = \Archive
    }
}

service auth {
    unix_listener /var/spool/postfix/private/auth {
        mode = 0660
        user = postfix
        group = postfix
    }
}
service lmtp {
    unix_listener /var/spool/postfix/private/dovecot-lmtp {
        mode = 0600
        user = postfix
        group = postfix
    }
}

protocol lmtp {
    postmaster_address = postmaster@%{user | domain}
    mail_plugins {
        sieve = yes
    }
}
protocol pop3 {
    pop3_no_flag_updates = yes
}

sieve_script personal {
    path = ~/.dovecot.sieve
}
sieve_script default {
    type = default
    name = default
    path = $SIEVE_DIR/default.sieve
}
EOF
	render_dovecot_tls_24
}

install_rendered_file() {
	tmp_file=$1
	destination=$2
	mode=$3
	if [ -f "$destination" ]; then
		cp -p "$destination" "$destination.emailwiz-previous"
	fi
	mv "$tmp_file" "$destination"
	chmod "$mode" "$destination"
}

render_dovecot() {
	require_active_domains
	detect_dovecot
	mkdir -p "$(dirname "$DOVECOT_CONF")"
	tmp_conf=$(mktemp "$(dirname "$DOVECOT_CONF")/.emailwiz-dovecot.XXXXXX")
	tmp_sql=''
	if [ "$DOVECOT_FAMILY" = 2.3 ]; then
		tmp_sql=$(mktemp "$(dirname "$DOVECOT_SQL_CONF")/.emailwiz-sql.XXXXXX")
		render_dovecot_sql_23 > "$tmp_sql"
		chmod 0640 "$tmp_sql"
		render_dovecot_23 > "$tmp_conf"
	else
		render_dovecot_24 > "$tmp_conf"
	fi
	chmod 0644 "$tmp_conf"

	if [ -n "$tmp_sql" ]; then
		install_rendered_file "$tmp_sql" "$DOVECOT_SQL_CONF" 0640
		if [ "${EMAILWIZ_TEST_MODE:-0}" != 1 ]; then
			chown root:dovecot "$DOVECOT_SQL_CONF"
		fi
		tmp_sql=''
	fi
	if [ "${EMAILWIZ_TEST_MODE:-0}" != 1 ]; then
		doveconf -c "$tmp_conf" -n >/dev/null
	fi
	install_rendered_file "$tmp_conf" "$DOVECOT_CONF" 0644
	if [ "$DOVECOT_FAMILY" = 2.4 ] && [ -f "$DOVECOT_SQL_CONF" ]; then
		rm -f "$DOVECOT_SQL_CONF"
	fi
	metadata_set dovecot_version "$DOVECOT_VERSION"
	metadata_set dovecot_family "$DOVECOT_FAMILY"
}

render_postfix_tls() {
	load_canonical_tls
	postconf -e "myhostname=$CANONICAL_MAIL_HOSTNAME"
	postconf -e "smtpd_tls_key_file=$CANONICAL_CERT_DIR/privkey.pem"
	postconf -e "smtpd_tls_cert_file=$CANONICAL_CERT_DIR/fullchain.pem"
	# Clear any SNI map left by the earlier per-domain certificate model.
	postconf -e 'tls_server_sni_maps ='
}

render_opendkim_tables() {
	mkdir -p "$(dirname "$OPENDKIM_KEYTABLE")" "$(dirname "$OPENDKIM_SIGNINGTABLE")"
	tmp_key=$(mktemp "$(dirname "$OPENDKIM_KEYTABLE")/.emailwiz-keytable.XXXXXX")
	tmp_signing=$(mktemp "$(dirname "$OPENDKIM_SIGNINGTABLE")/.emailwiz-signingtable.XXXXXX")
	sql "SELECT name || '|' || dkim_selector FROM domains WHERE enabled = 1 ORDER BY id;" |
	while IFS='|' read -r domain selector; do
		printf '%s._domainkey.%s %s:%s:%s/%s/%s.private\n' "$selector" "$domain" "$domain" "$selector" "$DKIM_ROOT" "$domain" "$selector"
	done > "$tmp_key"
	sql "SELECT name || '|' || dkim_selector FROM domains WHERE enabled = 1 ORDER BY id;" |
	while IFS='|' read -r domain selector; do
		printf '*@%s %s._domainkey.%s\n' "$domain" "$selector" "$domain"
	done > "$tmp_signing"
	mv "$tmp_key" "$OPENDKIM_KEYTABLE"
	mv "$tmp_signing" "$OPENDKIM_SIGNINGTABLE"
	chmod 0644 "$OPENDKIM_KEYTABLE" "$OPENDKIM_SIGNINGTABLE"
}

render_all() {
	write_postfix_lookup_configs
	render_dovecot
	render_postfix_tls
	render_opendkim_tables
}

reload_services() {
	doveconf -n >/dev/null
	postfix check
	for service_name in opendkim postfix dovecot; do
		systemctl reload "$service_name"
	done
}

system_render() {
	require_root
	require_database
	no_reload=0
	while [ "$#" -gt 0 ]; do
		case "$1" in
			--no-reload) no_reload=1; shift ;;
			*) die "Unknown system render option: $1" ;;
		esac
	done
	render_all
	[ "$no_reload" -eq 1 ] || reload_services
	say "Rendered configuration for Dovecot $DOVECOT_VERSION ($DOVECOT_FAMILY syntax)."
}
